set nocompatible

"set colorscheme
colorscheme delek
set background=dark

execute pathogen#infect()
call pathogen#helptags() " generate helptags for everything in 'runtimepath'
syntax on
filetype plugin indent on
set laststatus=2


"allow backspacing over everything in insert mode
set backspace=indent,eol,start

"store lots of :cmdline history
set history=1000

set showcmd     "show incomplete cmds down the bottom
set showmode    "show current mode down the bottom

set number      "show line numbers

set incsearch   "find the next match as we type the search
set hlsearch    "hilight searches by default

set wrap        "dont wrap lines
set linebreak   "wrap lines at convenient points

set ruler       "show current position

"default indent settings
set shiftwidth=2
set softtabstop=2
set expandtab
set autoindent

"set indentation colours
let g:indentLine_color_term = 10

"folding settings
set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default

"set wildmenu tab completion for cmdline
set wildmode=list:longest   "make cmdline tab completion similar to bash
set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing

set formatoptions-=o "dont continue comments when pushing o/O

"vertical/horizontal scroll off settings
set scrolloff=3
set sidescrolloff=7
set sidescroll=1

"load filetype-plugins and indent files
filetype plugin on
filetype indent on

"turn on syntax highlighting
syntax on

"set autoread to update files if saved externally to vim
set autoread

"some stuff to get the mouse going in term
set mouse=a
set ttymouse=xterm2

"tell the term has 256 colors
set t_Co=256

"hide buffers when not displayed
set hidden

"nerdtree settings
let g:NERDTreeMouseMode = 2
let g:NERDTreeWinSize = 40
"
""explorer mappings
nnoremap <f1> :BufExplorer<cr>
nnoremap <f2> :NERDTreeToggle<cr>
nnoremap <f3> :TagbarToggle<cr>
nnoremap <f4> :GundoToggle<cr>

"open *.md files in Google to preview them
noremap <F5> :!google-chrome file://%:p > /dev/null<CR><CR>

"Split Window mappings
nnoremap <f12> :botright vnew<cr>
nnoremap <f10> :topleft new<cr>

"Remap ; to : (so dont need to hit shift+;)
nnoremap ; :
vnoremap ; :

"set shortcuts for tab commands
nnoremap tt :tabnext<CR>
nnoremap tn :tabnew<CR>
nnoremap td :tabclose<CR>

"Indentation Guides
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1
nnoremap ig :IndentGuidesToggle<CR>

let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=233
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=234
autocmd VimEnter *  :IndentGuidesToggle
