set nocompatible

"set colorscheme
colorscheme delek
set bg=dark

execute pathogen#infect()
call pathogen#helptags()   " generate helptags for everything in 'runtimepath'
set laststatus=2
set encoding=utf-8

" === Set some useful stuff ===

set backspace=indent,eol,start "allow backspacing over everything in insert mode

set history=1000 "store lots of :cmdline history

set showcmd     "show incomplete cmds down the bottom
set showmode    "show current mode down the bottom
set title       "change the terminal's title

set number      "show line numbers

set ignorecase  "ignore case when searching
set incsearch   "find the next match as we type the search
set hlsearch    "hilight searches by default

set wrap        "dont wrap lines
set linebreak   "wrap lines at convenient points

set ruler       "show current position

set noshowmode  "dont show the current mode as its already in the status bar.

set hidden      "I like buffers and undo buffers, so dont close them

"never ever let Vim write a backup file! Use modern ways for tracking your changes, for God’s sake.
set nobackup
set noswapfile

"default indent settings
set shiftwidth=2
set softtabstop=2
set expandtab
set autoindent
set fo=tcq

"folding settings
set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default

"set wildmenu tab completion for cmdline
set wildmode=list:longest   "make cmdline tab completion similar to bash
set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing

set formatoptions-=o "dont continue comments when pushing o/O

"vertical/horizontal scroll off settings
set scrolloff=5
set sidescrolloff=7
set sidescroll=1

"load filetype-plugins and indent files
filetype plugin on
filetype indent on

"turn on syntax highlighting
syntax on

set autoread "set autoread to update files if saved externally to vim

"some stuff to get the mouse going in term
set mouse=a
set ttymouse=xterm2

set t_Co=256 "tell the terminal has 256 colors

"highlight annoying whitespace
autocmd filetype html,xml set listchars-=tab:>. "execpt where highlighting is annoying


" Change Comment colour from blue to cyan
highlight comment ctermfg=cyan


"nerdtree settings
let g:NERDTreeMouseMode = 2
let g:NERDTreeWinSize = 40


""explorer mappings
nnoremap <f1> :BufExplorer<cr>
nnoremap <f2> :NERDTreeToggle<cr>
nnoremap <f3> :TagbarToggle<cr>
nnoremap <f4> :GundoToggle<cr>

"open *.md files in Google to preview them
noremap <F5> :!google-chrome file://%:p > /dev/null<CR><CR>

"map paste for insert mode
set pastetoggle=<f12>

"Remap ; to : (so dont need to hit shift+;)
nnoremap ; :
vnoremap ; :

"I like tabs so... set shortcuts for tab commands
nnoremap tt :tabnext<CR>
nnoremap tn :tabnew<CR>
nnoremap td :tabclose<CR>

